name: Waka Readme

on:
  push:
    branches:
      - master
  schedule:
    - cron: '40 20 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: quincysky/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WATATIME_API_KEY }}
