name: Waka Readme
 
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: '0 0 * * *'
 
jobs:
  update-readme:
    permissions: write-all
    name: Update this repo's README 
    runs-on: ubuntu-latest
    steps:
      - uses: quincysky/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: ->
          SHOW_TIME: true
          TIME_RANGE: all_time
          SHOW_MASKED_TIME: true
          LANG_COUNT: 10
